version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: docker-compose up
      - run: yarn test
